---

- name: Record installed kernel version == current kernel version
  block:
    - name: Stat vmlinuz
      ansible.builtin.stat:
        path: "{{ '/tuxifier-sysroot/boot/vmlinuz-' ~ ansible_facts['kernel'] }}"
      register: _vmlinuz

    - name: Set_fact current_version_installed
      ansible.builtin.set_fact:
        current_version_installed: "{{ _vmlinuz.stat.exists }}"

- name: "Set root password"
  ansible.builtin.command:
    argv:
      - chroot
      - /tuxifier-sysroot
      - /bin/sh
      - -c
      - "echo {{ rootpw }}|passwd --stdin root"
  register: postminimallinstall__passwd
  failed_when: postminimallinstall__passwd.rc != 0

- name: "Add root authorized_keys to chroot"
  block:
    - name: Read authorized_keys
      ansible.builtin.slurp:
        src: /root/.ssh/authorized_keys
      register: _authorized_keys

    - name: Set_fact authorized_keys
      ansible.builtin.set_fact:
        authorized_keys: "{{ _authorized_keys['content'] | b64decode | split('\n') | reject('equalto', '') }}"

    - name: Write authorized_keys
      ansible.posix.authorized_key:
        key: "{{ item }}"
        path: /tuxifier-sysroot/root/.ssh/authorized_keys
        user: root
      loop: "{{ (authorized_keys + root_authorized_keys) | unique | reject('equalto', '') }}"

- name: Detect EFI
  block:
    - name: Stat /sys/firmware/efi
      ansible.builtin.stat:
        path: "/sys/firmware/efi"
      register: _efi

    - name: Set_fact grub_target
      ansible.builtin.set_fact:
        grub_target: "{% if _efi.stat.exists %}x86_64-efi{% else %}i386-pc{% endif %}"

- name: Set_fact boot_disk when not in hosts_vars
  ansible.builtin.set_fact:
    boot_disk: "{{ installdisk.boot_disk | default(installdisk.disks[0].device) }}"
  when:
    - installdisk.disks | default([]) | length == 1

- name: Set_fact boot_disk when multiple disks in installdisk in hosts_vars
  ansible.builtin.set_fact:
    boot_disk: "{{ installdisk_boot_disk | default('') }}"
  when:
    - installdisk.disks | default([]) | length >= 2

- name: Validate boot_disk
  ansible.builtin.assert:
    that:
      - boot_disk | default('', true) | string | trim != ''
    fail_msg: "boot_disk in not defined. Set this in hosts_vars when there are more then one disks in installdisk."

- name: Install grub2 to boot_disk for BIOS
  when: grub_target == "i386-pc"
  ansible.builtin.command:
    cmd: "chroot /tuxifier-sysroot grub2-install --target=i386-pc --recheck {{ boot_disk }}"
  changed_when: true

- name: Install grub2 at efi
  when: grub_target == "x86_64-efi"
  block:
    - name: Set_fact efi partitionnr
      ansible.builtin.set_fact:
        efi_partitionnr: >-
          {{
          installdisk.disks
          | map(attribute='partitions')
          | flatten
          | selectattr('id', 'equalto', 'efi')
          | map(attribute='number')
          | first
          }}

    - name: Set_fact _efibootmgr
      ansible.builtin.set_fact:
        _efibootmgr: "{{ efibootmgr | default('/usr/sbin/efibootmgr') }}"

    - name: Read existing EFI boot entries
      ansible.builtin.command: "chroot /tuxifier-sysroot {{ _efibootmgr }}"
      register: efibootmgr_entries
      changed_when: false

    - name: Remove existing efi entries
      ansible.builtin.command:
        argv:
          - chroot
          - /tuxifier-sysroot
          - "{{ _efibootmgr }}"
          - --delete-bootnum
          - -b
          - "{{ item }}"
      loop: "{{ efibootmgr_entries.stdout_lines | select('match', '.*' ~ (installdistribution.name | capitalize) ) | map('replace', 'Boot', '') | map('replace', '* ' ~ (installdistribution.name | capitalize),'')}}"
    - name: Install grub2 at efi
      ansible.builtin.command: >
        chroot /tuxifier-sysroot {{ _efibootmgr }} --remove-dups --create --disk {{ boot_disk }}
        --part {{ efi_partitionnr }}
        --label {{ installdistribution.name | capitalize }}
        --loader '\EFI\{{ installdistribution.name }}\shimx64.efi'
      changed_when: false

    - name: "Install grub2 at /boot/efi/EFI/<distribution.name>/grub.cfg for RHEL8"
      when: distribution.version == "8"
      ansible.builtin.command:
        cmd: "chroot /tuxifier-sysroot /usr/sbin/grub2-mkconfig -o /boot/efi/EFI/{{ distribution.name }}/grub.cfg"
      register: finalize__grub2_mkconfig
      failed_when: finalize__grub2_mkconfig.rc != 0

- name: "Install grub2 /boot/grub2/grub.cfg"
  ansible.builtin.command:
    cmd: "chroot /tuxifier-sysroot /usr/sbin/grub2-mkconfig -o /boot/grub2/grub.cfg"
  register: finalize__grub2_mkconfig
  failed_when: finalize__grub2_mkconfig.rc != 0

- name: "Discover host keys"
  ansible.builtin.find:
    path: "/etc/ssh/"
  register: etc_ssh

- name: Set_fact ssh_keys and ssh_pubs
  ansible.builtin.set_fact:
    ssh_keys: "{{ etc_ssh.files | map(attribute='path') | select('match', '.*key$') }}"
    ssh_pubs: "{{ etc_ssh.files | map(attribute='path') | select('match', '.*pub$') }}"

- name: "Install ssh host keys"
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: /tuxifier-sysroot/etc/ssh/
    remote_src: true
    mode: '0600'
  loop: "{{ ssh_keys }}"

- name: "Install ssh host pub keys"
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: /tuxifier-sysroot/etc/ssh/
    remote_src: true
    mode: '0644'
  loop: "{{ ssh_pubs }}"
  tags: debug

- name: "Relabel /bambini-sysroot"
  ansible.builtin.command:
    cmd: chroot /tuxifier-sysroot /usr/sbin/fixfiles -F onboot
  when: '(strict_selinux | default(false) | bool) and not (continue_install | default(false) | bool)'
