---

- name: "Copy a /certs/ca-bundle.trust.crt"
  ansible.builtin.copy:
    src: etc/ssl/certs/ca-bundle.crt
    dest: /etc/pki/tls/certs/
    mode: '0644'

- name: "Create /etc"
  ansible.builtin.file:
    path: /tuxifier-sysroot/etc
    state: directory
    mode: '0755'

- name: Correct fstab entries
  ansible.builtin.replace:
    path: /tmp/fstab
    regexp: "/tuxifier-sysroot"
    replace: ""

- name: "Write /etc/fstab"
  ansible.builtin.copy:
    remote_src: true
    src: /tmp/fstab
    dest: /tuxifier-sysroot/etc/fstab
    mode: '0644'

- name: "Mkdirs /dev /sys and /proc"
  ansible.builtin.file:
    path: "/tuxifier-sysroot{{ item }}"
    state: directory
    mode: '0755'
  loop:
    - "/dev"
    - "/proc"
    - "/sys"

- name: See if we're boot with efi
  ansible.builtin.stat:
    path: /sys/firmware/efi
  register: _efi

- name: Determine virtual_filesystems to mount
  ansible.builtin.set_fact:
    virtual_filesystems_to_mount: >-
      {{
        virtual_filesystems
        if _efi.stat.exists
        else virtual_filesystems
        | rejectattr('src', 'equalto', 'efivarfs')
        | list
      }}

- name: Mount all virtual_filesystems
  ansible.posix.mount:
    path: "{{ '/tuxifier-sysroot' ~ item.path }}"
    src: "{{ item.src }}"
    fstype: "{{ item.src }}"
    opts: "{{ item.opts }}"
    state: ephemeral
  loop: "{{ virtual_filesystems_to_mount }}"

- name: "Copy resolv.conf to chroot"
  ansible.builtin.copy:
    remote_src: true
    src: /etc/resolv.conf
    dest: /tuxifier-sysroot/etc/
    mode: '0644'
